name: community-platform-dev

services:
  community-platform-service:
    image: community-platform-image:latest
    container_name: community-platform
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx-service:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app-network
    depends_on:
      - community-platform-service

networks:
  app-network:
    driver: bridge