name: Platform Stage

on:
  push:
    branches: [ main ]
  # allow trigger manually
  workflow_dispatch:

jobs:
  build-and-deploy-stage:
    name: Build and deploy on stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: "install dependencies"
        run: npm install
      - name: "run tests"
        run: npm test
      - name: "build application"
        run: npm run build
        env:
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY_STAGE}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL_STAGE}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET_STAGE}}
          DATABASE_URL: ${{secrets.DATABASE_URL_STAGE}}
      - name: deploy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_STAGE }}
          username: ${{ secrets.USERNAME_STAGE }}
          passphrase: ${{ secrets.PASSPHRASE_STAGE }}
          port: ${{ secrets.PORT_STAGE }}
          source: "build,public/build"
          target: ${{ secrets.TARGET_DIR_STAGE }}
