name: Platform Stage

on:
  push:
    branches: [ main ]
  # allow trigger manually
  workflow_dispatch:

jobs:
  build-and-deploy-stage:
    name: Build and deploy on stage
    runs-on: ubuntu-latest
    steps:
      - name: "hello world"
        run: echo "Hello World"